using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows.Forms;
using DXP;
using EDP;
using SCH;
using PCB;
using System.IO;
using System.Xml.Serialization;
using System.Security;
using System.Security.Policy;
using System.Runtime.Remoting;

public class Commands
{
    //Autogenerated code. Commands implementation. Begin
    //Autogenerated code. Begin of implementation [GetState_BoardData]
    public void GetState_Screen(IServerDocumentView argContext, ref string argParameters, ref bool argEnabled, ref bool argChecked, ref bool argVisible, ref string argCaption, ref string argImageFile)
    {
        //To Do : Insert code here
    }
    //Autogenerated code. End of implementation [GetState_BoardData]

    //Autogenerated code. Begin of implementation [Command_BoardData]
    public void Command_Screen(IServerDocumentView view, ref string parameters)
    {
        MessageBox.Show("it work!");
        //new AltiumAssembly();
    }
    //Autogenerated code. End of implementation [Command_BoardData]

    //Autogenerated code. Commands implementation. End
}

